channels:
- conda-forge
dependencies:
- python=3.10.2
- pip<=24.0
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.0
  - pandas==2.2.1
  - pyyaml==6.0.1
  - torch==2.2.2
  - tqdm==4.66.2
name: mlflow-env
