[connections.mysql]
dialect = "mysql"
host = "bt4301-datawarehouse1.cxmwooi4whw1.ap-southeast-1.rds.amazonaws.com"
port = 3306
database = "BT4301_G09_DataWarehouse"
username = "admin"
password = "bt4301dw1"